server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/db_users
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: none
  liquibase:
    enabled: true
minio:
  secure: false
  bucket-name: test
  url: minio
  accessKey: access_key
  secretKey: secret_key

users:
  uri: http://jsonplaceholder.typicode.com/users